/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app;

import java.awt.*;

/**
 *
 * @author ferdy
 */
public class Camera extends javax.swing.JPanel {
    private final Main container;
    private Image image;
    private volatile boolean showGrid = false;
    private volatile String countdownText = "";

    /**
     * Creates new form Camera
     */
    public Camera(Main container) {
        initComponents();
        
        this.container = container;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if(image != null) {
            int width = getWidth();
            int height = getHeight();
            g.drawImage(image, 0, 0, width, height, null);

            if(showGrid) {
                g.setColor(new Color(255, 255, 255, 120));

                // Líneas verticales
                g.drawLine(width / 3, 0, width / 3, height);
                g.drawLine((width * 2) / 3, 0, (width * 2) / 3, height);

                // Líneas horizontales
                g.drawLine(0, height / 3, width, height / 3);
                g.drawLine(0, (height * 2) / 3, width, (height * 2) / 3);
            }

            if(!countdownText.isEmpty()) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setFont(new Font("Arial", Font.BOLD, 200));
                g2.setColor(new Color(255, 255, 255, 200));

                FontMetrics fm = g2.getFontMetrics();
                int x = (getWidth() - fm.stringWidth(countdownText)) / 2;
                int y = ((getHeight() - fm.getHeight()) / 2) + fm.getAscent();
                g2.drawString(countdownText, x, y);
            }
        }
    }
    
    public void setImage(Image image) {
        this.image = image;
    }

    public void setShowGrid(boolean showGrid) {
        this.showGrid = showGrid;
        repaint();
    }

    public void setCountdownText(String countdownText) {
        this.countdownText = countdownText;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
