package com.app;

import com.app.palette.FilterItem;
import com.app.palette.FilterItemRenderer;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.plaf.basic.BasicComboPopup;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.videoio.VideoCapture;

import static com.app.OpenCvUtils.matToImage;

/**
 *
 * @author ferdy
 */
public class Main extends javax.swing.JFrame {
    private Camera panelCamera;
    private Image image = null;
    
    private VideoCapture videoCapture = new VideoCapture(0);
    private MatOfByte mem = new MatOfByte();
    private Mat frame = new Mat();
    
    private List<FilterItem> filterItems;
    private FilterItem selectedFilter;
    private JList<?> filterList = null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Camera");
        
        panelCamera = new Camera(this);
        jPanel1.add(panelCamera, BorderLayout.CENTER);
        
        filterItems = new ArrayList<>();
        filterItems.add(new FilterItem("Normal", null));
        filterItems.add(new FilterItem("Blanco y negro", null));
        filterItems.add(new FilterItem("Sepia", null));
        filterItems.add(new FilterItem("Invertir", null));
        filterItems.add(new FilterItem("Mapa de calor", null));

        for(FilterItem filterItem:filterItems) {
            comboBoxFilter.addItem(filterItem);
        }
        
        selectedFilter = filterItems.getFirst();
        
        if (videoCapture.read(frame) && !frame.empty()) {
            // Esto "calienta" los FilterItem con imágenes antes de que el usuario interactúe.
            updateFilterComboBox();
        }
        
        comboBoxFilter.setRenderer(new FilterItemRenderer());
        findFilterList(comboBoxFilter);
        clock.start();
        updateFilterComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        comboBoxFilter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(102, 255, 102));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(50, 4));
        jToolBar1.setMinimumSize(new java.awt.Dimension(50, 4));
        jToolBar1.setPreferredSize(new java.awt.Dimension(50, 25));
        jSplitPane1.setLeftComponent(jToolBar1);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setSize(new java.awt.Dimension(300, 500));

        jSplitPane1.setRightComponent(jPanel1);

        jSplitPane1.addPropertyChangeListener(JSplitPane.DIVIDER_LOCATION_PROPERTY, new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if(jSplitPane1.getDividerLocation() > 150) {
                    jSplitPane1.setDividerLocation(150);
                }
            }
        });

        comboBoxFilter.setMaximumSize(new java.awt.Dimension(32767, 100));
        comboBoxFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(comboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            clock.stop();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowClosed

    private void comboBoxFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFilterActionPerformed
        selectedFilter = (FilterItem) comboBoxFilter.getSelectedItem();
    }//GEN-LAST:event_comboBoxFilterActionPerformed
  
    Timer clock = new Timer(70, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                if(!videoCapture.read(frame) || frame.empty()) {
                    clock.stop();
                    return; 
                }
         
                Mat filterFrame = new Mat();
                if(selectedFilter.getName().equals("Blanco y negro")) {
                    Imgproc.cvtColor(frame, filterFrame, Imgproc.COLOR_BGR2GRAY);
                }
                else if(selectedFilter.getName().equals("Sepia")) {
                    filterFrame = OpenCvUtils.applySepiaFilter(frame);
                }
                else if(selectedFilter.getName().equals("Invertir")) {
                    Core.bitwise_not(frame, filterFrame);
                }
                else if(selectedFilter.getName().equals("Mapa de calor")) {
                    Imgproc.applyColorMap(frame, filterFrame, Imgproc.COLORMAP_JET);
                }
                else {
                    filterFrame = frame;
                }
                      
                Imgcodecs.imencode(".bmp", filterFrame, mem);
                image = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                    
                panelCamera.setImage(image);
                panelCamera.updateUI();
                    
                if (comboBoxFilter.isPopupVisible()) {
                    updateFilterComboBox();
                }
                
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    });
    
    private void findFilterList(JComboBox<?> comboBox) {
        SwingUtilities.invokeLater(() -> {
            if (comboBox.getUI() instanceof BasicComboBoxUI ui) {
                if (ui.getAccessibleChild(comboBox, 0) instanceof BasicComboPopup popup) {
                    filterList = popup.getList();
                }
            }
        });
    }
    
    private void updateFilterComboBox() {
        //normal
        filterItems.getFirst().setPreviewImage(matToImage(frame));

        //black and white
        Mat grayFrame = new Mat();
        Imgproc.cvtColor(frame, grayFrame, Imgproc.COLOR_BGR2GRAY);
        filterItems.get(1).setPreviewImage(matToImage(grayFrame));

        //sepia
        Mat sepiaFrame = OpenCvUtils.applySepiaFilter(frame);
        filterItems.get(2).setPreviewImage(matToImage(sepiaFrame));

        //invert
        Mat invertFrame = new Mat();
        Core.bitwise_not(frame, invertFrame);
        filterItems.get(3).setPreviewImage(matToImage(invertFrame));

        //colormap
        Mat colorMapFrame = new Mat();
        Imgproc.applyColorMap(frame, colorMapFrame, Imgproc.COLORMAP_JET);
        filterItems.get(4).setPreviewImage(matToImage(colorMapFrame));

        if (filterList != null) {
            filterList.repaint();
            comboBoxFilter.repaint();
        }
    }
    
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<FilterItem> comboBoxFilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
