/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app;

import javax.swing.*;

/**
 *
 * @author ferdy
 */
public class PanelBottomControls extends javax.swing.JPanel {

    /**
     * Creates new form PanelBottomControls
     */
    public PanelBottomControls() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTimer = new javax.swing.JLabel();
        comboBoxTimer = new javax.swing.JComboBox<>();
        buttonCapture = new javax.swing.JButton();
        toggleButtonGrid = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(400, 50));

        labelTimer.setText("Temporizador:");
        add(labelTimer);

        comboBoxTimer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desactivado", "3 segundos", "5 segundos", "10 segundos" }));
        add(comboBoxTimer);

        buttonCapture.setText("Capturar");
        add(buttonCapture);

        toggleButtonGrid.setText("▦");
        add(toggleButtonGrid);
    }// </editor-fold>//GEN-END:initComponents


    public JComboBox<String> getComboBoxTimer() {
        return comboBoxTimer;
    }

    public JButton getButtonCapture() {
        return buttonCapture;
    }

    public JToggleButton getToggleButtonGrid() {
        return toggleButtonGrid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCapture;
    private javax.swing.JComboBox<String> comboBoxTimer;
    private javax.swing.JLabel labelTimer;
    private javax.swing.JToggleButton toggleButtonGrid;
    // End of variables declaration//GEN-END:variables
}
